spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dickieyang/spring-cloud-repo/
server:
  port: 9004
#如果我们的Git仓库需要权限访问，那么可以通过配置下面的两个属性来实现；
#spring.cloud.config.server.git.username：访问Git仓库的用户名
#spring.cloud.config.server.git.password：访问Git仓库的用户密码
# 配置服务注册中心
eureka.client.serviceUrl.defaultZone: http://localhost:8888/eureka/

management.security.enabled: false

##config rabbitmq
spring.rabbitmq.host: 192.168.31.42
spring.rabbitmq.port: 5672
spring.rabbitmq.username: root
spring.rabbitmq.password: Chkj2017